import os
from pathlib import Path
from dotenv import load_dotenv
from groq import Groq
import json

# importing our actual tool/function
from tools.weather import get_weather


# load stuff from .env
load_dotenv()

# grab Groq API key
my_groq_api = os.getenv("GROQ_API_KEY")

# just making sure the key actually exists
if not my_groq_api:
    raise ValueError("API key not found")


# create Groq client
client = Groq(api_key=my_groq_api)

model = "llama-3.3-70b-versatile"
role = "user"


# --------------------------------------------------
# TOOL DEFINITION
# --------------------------------------------------
# Here we're basically telling the LLM:
# "yo, you have this tool available if you need it"
#
# IMPORTANT:
# this does NOT actually run get_weather()
# it only tells the AI:
# - tool name
# - what it does
# - what arguments it needs

tools = [
    {
        "type": "function",
        "function": {
            "name": "get_weather",

            # helps the AI understand when this tool should be used
            "description": "Get the current weather for a city",

            # basically the input format/schema for our function
            "parameters": {
                "type": "object",
                "properties": {
                    "city": {
                        "type": "string",
                        "description": "The city to get the weather for"
                    }
                },

                # city must be provided
                "required": ["city"]
            }
        }
    }
]


# --------------------------------------------------
# USER MESSAGE
# --------------------------------------------------

msg = input("Ask : ")

message = {
    "role": role,
    "content": msg
}

messages = [message]


# --------------------------------------------------
# FIRST LLM CALL
# --------------------------------------------------
# We send:
# 1. user's message
# 2. available tools
#
# tool_choice="auto" means:
# LLM decides whether it needs a tool or not

res = client.chat.completions.create(
    model=model,
    messages=messages,
    tools=tools,
    tool_choice="auto"
)

print()


# --------------------------------------------------
# GET THE TOOL CALL
# --------------------------------------------------
# If the AI decides:
# "I need weather data"
#
# it returns a tool_call instead of actually calling
# the Python function itself.
#
# We're grabbing the first requested tool here.

tool_call = res.choices[0].message.tool_calls[0]

print("\nTool Call:")
print(tool_call)


# --------------------------------------------------
# GET ARGUMENTS GENERATED BY AI
# --------------------------------------------------
# arguments usually comes back as a JSON STRING
#
# something like:
# '{"city":"Bhopal"}'

arguments = tool_call.function.arguments


# convert JSON string -> Python dictionary
#
# '{"city":"Bhopal"}'
# becomes
# {"city": "Bhopal"}

arguments = json.loads(arguments)

print("\nArguments:")
print(arguments)


# --------------------------------------------------
# ACTUALLY RUN THE TOOL
# --------------------------------------------------
# THIS is where our Python function actually runs.
#
# Important idea:
# LLM asked us to call the tool.
# Our Python code is the one actually calling it.

tool_result = get_weather(arguments["city"])

print("\nTool Result:")
print(tool_result)


# --------------------------------------------------
# SAVE AI'S TOOL REQUEST IN MESSAGE HISTORY
# --------------------------------------------------
# We need this because the next LLM call needs to know:
# "oh yeah, I requested this tool earlier"

messages.append(res.choices[0].message)


print("\nTool Call ID:")
print(tool_call.id)


print("\nMessages:")
print(messages)


# --------------------------------------------------
# GIVE TOOL RESULT BACK TO THE AI
# --------------------------------------------------
# Now we're saying:
#
# "here's the result of the tool you asked for"
#
# tool_call_id connects this result with the
# exact tool request the AI made.

messages.append({
    "role": "tool",
    "tool_call_id": tool_call.id,
    "content": json.dumps(tool_result)
})

print(messages)


# --------------------------------------------------
# SECOND LLM CALL
# --------------------------------------------------
# Now the AI has:
#
# user question
#      ↓
# its own tool request
#      ↓
# actual tool result
#
# So now it can use that data to generate
# a normal human-readable answer.

res = client.chat.completions.create(
    model=model,
    messages=messages,
    tools=tools,
    tool_choice="auto"
)


# --------------------------------------------------
# FINAL ANSWER
# --------------------------------------------------

print("\nFinal Answer:")
print(res.choices[0].message.content)

print()